[TEAM08] BE - 회원가입 기능, JWT 토큰을 이용한 로그인 기능 구현
codesquad-members-2024/issue-tracker pull request #22
Opened 2024-05-13 02:35 UTC by pjm2571

# 구현 사항

## 회원가입
- 회원가입 성공 여부에 따라 상태 코드로 동작하도록 구현
   - 성공 : `HttpStatus 200`
   - 실패
      - 회원가입 양식 오류 : `HttpStatus 400`
      - 중복 id 회원가입 오류 : `HttpStatus 409`

## 로그인
- 로그인 성공 시, JWT 토큰이 Cookie에 설정되도록 구현
  - 성공 : `HttpStatus 200` + HttpHeader에 JWT 토큰 설정
  - 실패 : `HttpStatus 401`
     - 아이디가 존재하지 않는 경우
     - 아이디는 존재하지만 비밀번호가 일치하지 않는 경우

## 로그인 검증
- 임시로 `member/validate` url에 `GET` 요청이 들어왔을 때 `JWT 토큰값` 에 대한 검증 구현

## 로그아웃
- POST로 `member/logout`으로 요청 전송 시, 쿠키가 만료되도록 구현

---

2024-05-13 13:44 UTC, moto6 requested changes
전반적으로 열심히 하시고 잘하려고 노력하신 부분이 인상깊어요 👍🙆🏻‍♂️

몇가지 제안사항과 이건 꼭 고쳐주시면 좋을꺼같은것들에 대해서 리뷰 남겨봤습니다! 

몇몇 부분들은 제가 바로 정답을 이야기해드릴수도 있는데요, 굳이 힌트만 남겨두고 정답을 말씀드리지 않은 부분이 몇가지가 있는데요, 기능을 구현하는 과정에서 하나하나 그때마다 짧게 CS 도 공부하고  
책도 처음부터 끝까지 정주행 하는게 아니라 일부분만 짧고 강렬하게 읽는다면  면접가서 결정적인 순간에 분명 도움이 되실꺼에요!

2024-05-13 13:44 UTC, moto6 commented on be/issue-tracker/src/main/java/team08/issuetracker/label/model/Label.java
> +    }
description 이 선택이라면 다른 프로퍼티들은 필수라는 의미로 해석할수도 있을꺼같은데요 

만약에 맞다면 이런 코드를 추가하면 어떨까요? 요거는 아마 회사다니면서 지옥의 NPE 무한굴레를 맛보기 전까지는 알기 힘든 기능이긴 해요 

```
public Label(String name, String description, String background_color, String text_color) {
        this.name = name;
        this.description = description;
        this.background_color = background_color;
        this.text_color = text_color;
        Assert.hasText(background_color,"배경색은 필수값입니다");
        Assert.hasLength(text_color,"문자의 색상은 필수값입니다");
        Assert.notNull(name,"필수필수");
    }
```
Assert.메서드() << 에서 다양한 메서드가 있다는거를 예시로 보여드린거니까 가장 적당해 보이는 메서드로 생성자에 검증로직을 넣어주세요!

2024-05-13 13:44 UTC, moto6 commented on be/issue-tracker/src/main/java/team08/issuetracker/label/model/dto/LabelCountDto.java
> +public class LabelCountDto {
dto 클래스라면 record 를 학습하고 도입해보면 어떨까요? 

https://www.baeldung.com/java-record-keyword

2024-05-13 13:44 UTC, moto6 commented on be/issue-tracker/src/main/java/team08/issuetracker/label/model/dto/LabelCountDto.java
> +public class LabelCountDto {
모든 dto 를 한번에 다 record 로 변경하면 너무 손이 많이 가니까 이번 PR 에서는 한두개 정도만 도입해보셔도 좋을꺼같습니다 (진짜 제안임 강요 XX)

2024-05-13 13:44 UTC, moto6 commented on be/issue-tracker/src/main/java/team08/issuetracker/label/model/Label.java
> +    private String text_color;
background_color 라는 이름보다 backgroundColor 라는 이름은 어떨까요? 

자바에서는 대체적으로 camel-case 를 사용해서요!  >> 이거 보고 문득 떠오른건데 저도 코쿼 첫 PR 에서 카멜케이스를 사용하지 않았던거같아요 ㅋㅋㅋ 🤣

https://google.github.io/styleguide/javaguide.html#s5.3-camel-case

요거는 특수한 상황(SQL 이라던지.. 문서, 외부 API ) 이 아니라면 모든 프로젝트에서 카멜케이스를 사용할수 있도록 해주세요!

2024-05-13 13:44 UTC, moto6 commented on be/issue-tracker/src/main/java/team08/issuetracker/member/service/MemberService.java
> +        }
메서드를 분리해낼수 있을꺼같아요!

2024-05-13 13:44 UTC, moto6 commented on be/issue-tracker/src/main/java/team08/issuetracker/member/service/MemberService.java
> +        }
요 부분도 각각 메서드로 분리해주세요!

2024-05-13 13:44 UTC, moto6 commented on be/issue-tracker/src/main/java/team08/issuetracker/member/service/MemberService.java
> +    private static final String PW_REGEX = "^(?=.*[a-zA-Z])(?=.*\\d)[a-zA-Z\\d]{6,12}$";
👍 정규표현식 상수를 ID_REGEX, PW_REGEX 라는 대문자 이름으로 분리해낸 부분은 잘하셨어요!

2024-05-13 13:44 UTC, moto6 commented on be/issue-tracker/src/main/java/team08/issuetracker/member/service/MemberService.java
> +        String password = memberCreationDto.getPassword();
여기서는 dto를 받는게 아니라 46번 라인처럼
```
private void validateLoginCredential(Member member, String inputPassword) {
```

memberId 와 password 를 분리해서 (그러니까 이 메서드를 호출하는 부분에서 dto 구조를 분해해서) 호출하면 조금 더 범용적이고 다른곳에서도 재사용가능한 메서드가 될꺼같아요! 

인수가 많으면 무조건 좋은건 아니긴 한데요, 함수의 인수의 갯수를 몇개로 정할지에 대한 고민이 생긴다면 

"클린코드 50p" << 참고로 요책 코쿼 책장에 있을꺼같습니다!

2024-05-13 13:44 UTC, moto6 commented on be/issue-tracker/src/main/java/team08/issuetracker/member/controller/MemberController.java
> +                .maxAge(7776000)
7776000 << 이것도 상수니까 분리해주면 어떨까요?
```
private static final TOKEN_DURATION_90DAYS = 90 * 24* 60 * 60
```
요런 느낌은 어떨까요?

2024-05-13 13:48 UTC, moto6 commented
+ 파일끝에 자동으로 개행문자가 추가되도록 요 글을 보고 IDE 설정도 추가하면 좋을꺼같아요!

https://velog.io/@d-h-k/intellij-파일끝에-개행을-자동으로-추가하는-방법

2024-05-13 13:55 UTC, moto6 commented
피드백 드린 부분 다 수정하고 다시한번더 멘션 or 슬랙체널에 공유해주시면 적절하게 수정해주셨는지 바로 확인할꼐요!!

2024-05-14 06:56 UTC, pjm2571 commented on be/issue-tracker/build.gradle
> +	implementation 'org.springframework.boot:spring-boot-starter-validation'
이상하네요 인텔리제이에서는 정렬되어 있는 상태로 나오는데... 또 여기서는 이렇게 나오네요..?

<img width="637" alt="image" src="https://github.com/codesquad-members-2024/issue-tracker/assets/97939207/32263d66-b6cc-4a37-83a7-e28ff150710c">

무슨 문제일까요???

2024-05-14 06:57 UTC, pjm2571 commented on be/issue-tracker/src/main/java/team08/issuetracker/exception/ExceptionController.java
> +    private String error_msg;
- [ ]  error_msg를 의도한 이유
    - error_msg는 String 문자열로 동작하는데, 이 값을 상수화해서 저장하지 않고, 따로 error_msg만 관리해주는 파일을 만들어서 그 파일에서 읽어오도록 구현하고 싶었음
    - `[message.properties](http://message.properties)` 와 같은 파일을 이용해서 에러 메세지 관리
    
    ...
    
    저번 프로젝트에서 했던 것 중에서 `message.properties` 라는 것을 통해 에러 메세지를 관리하시는 분이 계시더라구요! 그래서 이번 프로젝트에서 적용해보고 싶었는데, 좀 지금의 구현 상황과는 좀 관련이 없는 것 같아서 추후에 구현하려고 이렇게 구현을 했습니다..! 차라리 message.properties를 먼저 구현하는 것이 좋을까요?

2024-05-14 06:59 UTC, pjm2571 commented on be/issue-tracker/src/main/java/team08/issuetracker/jwt/JwtService.java
> +
- JWT 토큰 값을 터미널에서 확인하기 위해 `sout`을 사용!
    - log.debug로 변경 완료!

→ 로그를 표준출력으로 사용하지 않고, 파일로 저장하도록 구현하는 것이 더 좋음!

2024-05-14 07:01 UTC, pjm2571 commented on be/issue-tracker/src/main/java/team08/issuetracker/label/controller/LabelController.java
> +@CrossOrigin("*")
안그래도 저희도 cors에 대해서 고민이 많아서, honux께 한 번 여쭈어 봤었는데요.

지금 고려하기엔 조금 복잡한 문제라서, 전체에 대한 접근을 허용하도록 (*) 로 구현하고, 구현부터 해라.. 라고 말씀을 하셔서 단순히 이렇게 했던 것 같습니다..

저희 BE들끼리 리팩토링을 하면서 공부를 조금 더 해보겠습니다! 확실히 개념이 잡히면 한 번 더 리팩토링을 해보도록 하겠습니다.

todo list에 추가~!

2024-05-14 07:01 UTC, growth-mango commented on be/issue-tracker/src/main/java/team08/issuetracker/label/controller/LabelController.java
> +@CrossOrigin("*")
스포 감사합니다 💛

2024-05-14 07:07 UTC, pjm2571 commented on be/issue-tracker/src/main/java/team08/issuetracker/label/model/Label.java
> +    }
요 부분은 공부를 한 번 해보겠습니다~! 

쪼끔 낯설어서.. ㅎㅎ 잘 모르겠씁ㄴ디ㅏㅎ 흐드허엉

2024-05-14 07:13 UTC, pjm2571 commented on be/issue-tracker/src/main/java/team08/issuetracker/label/model/dto/LabelCountDto.java
> +public class LabelCountDto {
record 너무 좋은 것 같습니다!

저희가 db에서 가져온 값을 Server단에서 변경을 해주는 것이 아무것도 없기 때문에

1) Setter가 필요 없다
2) 데이터의 불변성을 유지해야된다.
3) 생성자가 1개 밖에 없다.

2024-05-14 07:14 UTC, pjm2571 commented on be/issue-tracker/src/main/java/team08/issuetracker/label/model/Label.java
> +    private String text_color;
요거는 ERD 다이어그램을 보면서 변수명을 작성하다 보니까 ㅋㅋㅋ 헷갈렸네요 ㅎㅎ ^.ㅠ

수정하겠습니다 ㅎㅎ

저희 코드 컨벤션도 카멜 케이스를 지키기로 약속했습니다~

2024-05-14 10:31 UTC, moto6 commented
<img width="696" alt="image" src="https://github.com/codesquad-members-2024/issue-tracker/assets/31065684/de24e738-eed2-4c51-ad07-45d6262e95de">

2024-05-14 10:55 UTC, moto6 commented
대부분은 잘 고쳐 주셨는데 몇몇 아쉬운 부분들이 있어서 추가 코멘트 남겨봤어요! 다음번 PR 에서는 반영 부탁드릴께요! 고생 많이하셨습니다!

2024-05-14 10:55 UTC, merged

2024-05-15 01:00 UTC, pjm2571 commented on be/issue-tracker/src/main/java/team08/issuetracker/member/model/dto/MemberCreationDto.java
> +}
오호 프로퍼티마다 개행을 주면 더 보기좋은 코드가 될 것 같아요! 감사합니다 ㅎㅎ 적용해보도록 하겠습니다!!

2024-05-15 01:01 UTC, pjm2571 commented
> 그리고 이건 중요한건 아닌데 처리완료된 코멘트 내용은 Resolve conversation 버튼을 눌러 주시면 감사하겠습니다 🫡 <img alt="image" width="696" src="https://private-user-images.githubusercontent.com/31065684/330389520-de24e738-eed2-4c51-ad07-45d6262e95de.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3MzQ5ODgsIm5iZiI6MTcxNTczNDY4OCwicGF0aCI6Ii8zMTA2NTY4NC8zMzAzODk1MjAtZGUyNGU3MzgtZWVkMi00YzUxLWFkMDctNDVkNjI2MmU5NWRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE1VDAwNTgwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQxMWE1ZWE2NTk1YjA3OTlkNDEyODRiYWQxNzgzMTM0YTlmN2I4Mzk3NDcxOGEzNzBlMDc0NWE0M2YzMDQ4NGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6Poh0vcAN9JBQfFXoGWJlZN6LACwCdoY4GTV7WsQkgU">

이런 기능이 있다는 걸 처음 알았네요 ㅎㅎ

말씀주신 사항 다음 PR에서는 열심히 반영해서 클린 코드로 한 번 올려보겠습니다~~ 고생하셨습니다 감사합니다 ㅎㅎ

2024-05-15 02:27 UTC, moto6 commented
## Wrap up
- 이번 PR 통과하시느라 고생하셨습니다. 일정상 제가 생각지 못한 고민이나 고려할 점이 있다면 어떤 방식으로든 공유해주시면 같이 고민해볼께요! 
- 요번 PR 마무리하면서 레슨런을 한번 정리해봤는데요 정답은 아니고 개인적인 견해이니 한번 읽고 넘겨주시면 감사하겠습니다!

### 레슨런

- code convention, format 맞추기
  - code convention : 기능동작에는 영향이 없는데도 불구하고 정말 중요합니다 뭐랄까.. 의사소통의 일종? 대화에서 "말투" 와 비슷한거같아요. 같은 맥락이라도 말투에 따라서 상대방이 다르게 반응할수 있잖아요?
    - 요건 이번 PR 에서도 잘 지켜주셨습니다! 🤗
  - code format 맞추기 : 저도 리뷰를 받가보면 가끔 format 을 놓칠때도 있는데, 그럴때면 어김없이 코드리뷰에 format 관련된 리뷰가 많이 달리더라고요. 그래서 정작 중요한 로직이나, 동작 관련된 사항들에 대해 이야기하는 비중이 줄어드는 경우가 있었던거같습니다. 그래서 역설적이게도 코드포멧팅과 컨벤션이 중요하지는 않지만, 중요한 요소인거같아요
    - build.gradle 코드정렬 : space문자와 tab 문자가 섞여있어서 그렇습니다! 요거를 쉽게 한방에 해결할수 있는 인텔리제이 기능이 있는데 아래 스샷 첨부해둘께요!
    - 파일끝 개행문자 자동추가되는 인텔리제이 설정 세팅도 같은 맥락입니다!

- 쉽게 실천해볼수 있는 코드 리팩토링 규칙
  - 메서드는 최대 3개 까지만의 argument 를 갖도록  만들어주세요!
  - 메서드는 최대 12라인을 넘어가지 않도록! 6라인이 넘어가는 메서드는 분리가 필요한게 아닐지 한번더 고민해봐주세요!
  - 한 메서드에서는 최대 2단계의 들여쓰기만! 그이상 들여쓰기가 필요하다면 꼭 메서드를 분리해봅시다!
  - 한줄에 점(.)은 하나만 찍어주세요!

- 장기과제 (나중에 해볼만한것들)
  - @CrossOrigin("*")
  - 테스트코드 : 학습테스트, 단위테스트 (테스트도 하나씩 가벼운 마음으로 추가해보면 좋을꺼같아요!)
    - 정규표현식을 사용하신 부분에 대해서 "우리가 의도한대로 잘 동작하는지 테스트할려면 어떻게 해야할까?" 여기서부터 테스트를 출발해도 좋을꺼같아요.
  - 클린코드 책 4장 주석 파트