[TEAM08] BE - 이슈 기능 구현
codesquad-members-2024/issue-tracker pull request #51
Opened 2024-05-20 02:35 UTC by shimbaa

# 구현한 기능

- 이슈 생성
	- `url` : `/issue`
	- `method` : `POST`

# 현재까지 구현한 내용

`Issue` 클래스의 껍데기라도 빠르게 구현 해보자 라는 마음으로 시작하였는데, 예상보다 생각할 포인트가 상당히 많아서 구현해나가야 하는 내용을 잘게 쪼개서 하나씩 해나가기로 하였습니다.

#### 결론 : `Issue`와 1:1 관계인 필드들, N:M 관계인 필드 중 `Assginee`(담당자)에 대한 내용만 반영하여 `Issue` 생성 기능 구현

---
#### `Issue` 클래스의 필드 분석
- 클라이언트로 부터 받는 값 (JSON으로 받는 값)
	(구현)
	* title 
	* writer 
	* content
	* file
	* assignees
---
	(구현 예정)
	* mileStones
	* labels
	* comments

- Issue 생성시 서버에서 부여되는 값
	(구현)
	- createdTime (생성시간)
	- isOpen (이슈가 열려있는지 / 생성시 기본값은 true)

---

클라이언트로 부터 받는 값들은 `IssueCreationDto`를 통해 받습니다.

SpringDataJdbc의 CrudRepository 기능 활용을 위해
Issue - Member 의 중간테이블 엔티티인 `Assignee` 클래스 구현, `AssigneeRepository`구현

## Issue 생성 흐름

Issue와 일대일 관계인 필드값들로 먼저 Issue 객체를 생성하여 DB에 저장합니다.
DB에서 autoIncrement로 pk인 id 값이 부여됩니다.

`Issue에 부여된 id 값` + `클라이언트로 부터 받은 memberId 값 (assigneeId)` 으로
Assignee 객체를 생성하고 DB에 저장합니다.
마찬가지로 DB에서 autoIncrement로 Assignee에 대한 pk인 id 값이 부여됩니다.

2024-05-20 21:52 UTC, moto6 requested changes
이번 미션도 잘 진행해주셨네요 몇가지 보이는 부분 피드백 드렸는데요, 확인해주시면 감사하겠습니다!

2024-05-20 21:52 UTC, moto6 commented on be/issue-tracker/src/main/java/team08/issuetracker/exception/member/MemberNotFoundException.java
> +    private static final String ERROR_MESSAGE = "존재하는 ID가 없습니다.";
요 MemberNotFoundException  라는 익셉션이 ERROR_MESSAGE 로 "존재하는 ID가 없습니다." 를 갖는게 어색합니다.

무슨말이냐면, Member 조회조건으로 다른 조건이 where절에 사용될수 있는데, id가 없어서 조회에 실패한건지, 다른 조건으로 조회해서 실패한건지가 결정되어있는, 클래스명과 에러메시지의 레이어? 관심사항의 레벨이 좀 다른 느낌이 들어요

2024-05-20 21:52 UTC, moto6 commented on be/issue-tracker/src/main/java/team08/issuetracker/exception/member/MemberNotFoundException.java
> +    private static final String ERROR_MESSAGE = "존재하는 ID가 없습니다.";
지금은 id로만 멤버를 가져오니까 괜찮을수 있는데 나중에 기능이 추가되서 다른 조건문(예를들면 이름+생일 같은 조건) 으로 검색했을떄 데이터 조회에 실패하는 익셉션을 만들어야하는 상황이 왔을때는 아래의 추가작업이 필요할수 있어보여요
1. 이 MemberNotFoundException  클래스를 재사용 하기 힘들다 > 에러메시지에 id때문이라고 박혀있으니까
2. MemberNotFoundException 의 이름을 변경하거나의 추가적인 조치가 들어간다

2024-05-20 21:52 UTC, moto6 commented on be/issue-tracker/src/main/java/team08/issuetracker/exception/milestone/MilestoneAlreadyClosedException.java
> +    public MilestoneAlreadyClosedException() {
요건 취향이긴 한데 그냥 의견만 남겨봅니다 (open, close 두 클래스 모두 동일의견입니다!)

open 되어있는걸 다시 open 하려고하면 당연히 처리할수 없는게 맞긴 한데요, 이걸 굳이 익셉션으로 던질 필요는 있을까요? 웹서핑 하다보면 확인차 버튼 한번 더 누르는경우도 있을수 있고요 컨트롤어드바이스에서 200응답을 내보내주면서 이미 처리되어있다 라고 안심하라구~ 메시지 보내줘도 되고, 처음부터 익셉션이 터지지 않게 한번더 처리해줘도 상관은 없을꺼같아요 

왜냐하면 그로인해서 데이터가 하나 더 생긴다거나 하지는 않으니까요! 요건 그냥 의견이라서 변경 안해도 좋고 바꾸셔도 상관없는 코멘트입니다!

2024-05-20 21:52 UTC, moto6 commented on be/issue-tracker/src/main/java/team08/issuetracker/exception/milestone/MilestoneNotFoundException.java
> +    private static final String ERROR_MESSAGE = "해당하는 id의 마일스톤을 찾을 수 없습니다.";
요기 부분도 MODEL NOT FOUND+에러메시지 id : Member 에서 언급한 내용과 동일한 부분인듯 합니다!

2024-05-20 21:52 UTC, moto6 commented on be/issue-tracker/src/main/java/team08/issuetracker/issue/controller/IssueController.java
> +        return ResponseEntity.ok(sb.toString());
ResponseEntity<String> 타입으로 리턴을 응답해주고 우리가 원하는 형태의 문자열로 포메팅 해주기 위해서 string builer 도 사용하고 계신대요, response 용 DTO 클래스를 정의해서 응답해준다면 JSON 형식으로 쉽게 변환할수 있을꺼같아요

https://devjaewoo.tistory.com/76

2024-05-20 21:52 UTC, moto6 commented on be/issue-tracker/src/main/java/team08/issuetracker/issue/model/Issue.java
> +    private LocalDateTime createdTime;
db 컬럼과 자바클래스 변수명 모두 createdAt 이라는 이름으로 주로 널리 사용하는거같아요 무조건 지켜야하는건 아닌데 대부분은 그렇게 하긴 하는데요..  데이터베이스에 타임스탬프라고 컬럼명이 되어있으면 이게 시간정보인거는 알겠는데 무슨말이지? 만든시간인가? 최종수정시간인가? 아니면 다른 시간을 저장해야하는 기능이 있는건가 혼동할 여지가 있어보여요

2024-05-20 21:52 UTC, moto6 commented on be/issue-tracker/src/main/java/team08/issuetracker/issue/model/dto/IssueCreationDto.java
> +                               List<Object> labels, List<String> assigneeIds, String file) {
```suggestion
public record IssueCreationDto(
    String title, 
    String writer, 
    String content, 
    Object mileStone,
    List<Object> labels, 
    List<String> assigneeIds, 
    String file
) {
```

2024-05-20 21:52 UTC, moto6 commented on be/issue-tracker/src/main/java/team08/issuetracker/issue/model/dto/IssueCreationDto.java
> +                               List<Object> labels, List<String> assigneeIds, String file) {
좌우 말고 상하로 컬럼을 배치하도록 정렬하면 훨씬 보기가 좋을꺼같아요!

2024-05-20 21:52 UTC, moto6 commented on be/issue-tracker/src/main/java/team08/issuetracker/issue/model/dto/IssueCreationDto.java
> +                               List<Object> labels, List<String> assigneeIds, String file) {
Object mileStone,
List<Object> labels,

오브젝트 타입이라는 아주 날것의 타입을 사용한 이유가 있을까요?

2024-05-20 21:52 UTC, moto6 commented on be/issue-tracker/src/main/java/team08/issuetracker/issue/service/IssueService.java
> +    @Transactional
아주좋습니다!

2024-05-20 21:52 UTC, moto6 commented on be/issue-tracker/src/main/java/team08/issuetracker/issue/ref/IssueAttachedLabel.java
> +}
다대다 연관관계를 위해 존재하는듯 한데요, `@Setter` 를 사용하면 객체 외부에서 아무런 제약없이 객체의 상태를 변경할수 있어요IssueAttachedLabel  객체 스스로가 특정 변수의 상태를 변경하기 위한 메서드를 만들고 제공해주면 어떨까요?

2024-05-20 21:52 UTC, moto6 commented on be/issue-tracker/src/main/java/team08/issuetracker/milestone/controller/MilestoneController.java
> +    }
(String.format("마일스톤 생성 성공! 마일스톤 #%d 이름 : %s", milestone.getId(), milestone.getName()) 이 부분과   ResponseEntity<String> 부분 모두 dto 클래스에서 처리할수 있도록 DTO 클래스를 만들고 분리해주면 좋을꺼같아요

2024-05-20 21:52 UTC, moto6 commented on be/issue-tracker/src/main/java/team08/issuetracker/milestone/service/MilestoneService.java
> +    private static final String CLOSE_STATE_QUERY = "closed";
STATE_QUERY 라는게 지금은 "opened" , "closed" 두개뿐이 없는데요 enum 클래스로 분리해내면 훨씬 좋아질꺼같은데요(의견입니다)

2024-05-20 21:52 UTC, moto6 commented on be/issue-tracker/src/main/java/team08/issuetracker/milestone/service/MilestoneService.java
> +    private static final boolean CLOSE_STATE = false;
요부분도 마일스톤 모델 클래스 내부로 이동해서 OPEN 상태인지 아닌지를 마일스톤 모델이 직접 판단하고 검사하는 메서드를 만드는건 어떨까요? 

마일스톤의 정보를 서비스 레이어에서 가지고 있어보여서요

2024-05-21 01:03 UTC, shimbaa commented on be/issue-tracker/src/main/java/team08/issuetracker/issue/controller/IssueController.java
> +        return ResponseEntity.ok(sb.toString());
참고자료까지 남겨주셔서 감사합니다😊 `@RestController`가 `@Controller` + `@ResponseBody`라는 것을 알게되었습니다.
위의 코드는 제가 임시로 코드 정상 동작하는지 확인 해보려 작성한 것이었습니다. 아직 응답 형식이 프론트와 정해지지 않아서요.
그래도 동께서 리뷰주신 내용 도움받아 최소한 제가 임의로라도 정한 json 형태로 응답하게 바꿔보겠습니다!

2024-05-21 01:25 UTC, pjm2571 commented on be/issue-tracker/src/main/java/team08/issuetracker/exception/ExceptionController.java
> +import team08.issuetracker.exception.milestone.*;
오오! code editor의 속성을 통해 해결할 수 있었습니다!

팀 노션에도 적어놓았지만, 리뷰를 통해 확인할 수 있게 트러블 슈팅 란에 링크 남기겠습니다~~

https://growth-mango.notion.site/Import-92c5299801be424a89b4315c7709ddef?pvs=4

2024-05-21 01:30 UTC, shimbaa commented on be/issue-tracker/src/main/java/team08/issuetracker/issue/model/dto/IssueCreationDto.java
> +                               List<Object> labels, List<String> assigneeIds, String file) {
IssueCreationDto 가 클라이언트에서 오는 값을 처음 받는 객체이다 보니, 어떤 값으로 넘어오게 될지 아직 정하지 못해서 저렇게 임의로 표현해두었던거 같습니다!
클라이언트에서 milestone id 값, label의 id 값들이 넘어온다고 상정하고 리팩토링 진행해보겠습니다!

2024-05-21 01:57 UTC, pjm2571 commented on be/issue-tracker/src/main/java/team08/issuetracker/exception/member/MemberIdDuplicateKeyException.java
> +public class MemberIdDuplicateKeyException extends DuplicateKeyException {
넵! 안그래도 리팩토링을 진행하려고 했던 부분인데, 한 번 수정해보겠습니다. key라는 이름보다는, id가 더 가시성이 있을 것 같아서 id로 선택하였습니다.

2024-05-21 02:03 UTC, pjm2571 commented on be/issue-tracker/src/main/java/team08/issuetracker/exception/member/MemberNotFoundException.java
> +    private static final String ERROR_MESSAGE = "존재하는 ID가 없습니다.";
맞아요! 안그래도 현재 `Member`  table이 column 값으로 `memberId`, `password`를 가지도록 구현하여서, `ID`로 조회하는 쿼리밖에 없다보니, `MemberNotFoundException` 으로 정의를 했습니다.

제가 개선하고자 하는 방향은, Exception 이름을 통해 어떤 예외인지 알 수 있게 하도록 하기 위해  `MemberIdNotFoundException`으로 개선하였습니다

2024-05-21 02:12 UTC, pjm2571 commented on be/issue-tracker/src/main/java/team08/issuetracker/exception/milestone/MilestoneAlreadyClosedException.java
> +    public MilestoneAlreadyClosedException() {
결국에 마일스톤의 `open`/`close` 상태를 바꾼다는 것은, DB에 저장된 테이블 필드 값을 바꾸는 것이기 때문에, `UNPROCESSABLE_ENTITY` 라는 에러 코드로 "서버가 요청 엔티티의 컨텐츠 형식을 이해했고 요청 엔티티의 문법도 올바르지만 요청된 지시를 처리할 수 없음" 을 표현하기 위해 구현하였습니다!

클라이언트에서 `open` 된 상태에서는  `닫기 버튼` 만 보여지고, `close` 상태에서는 `열기` 버튼만 보여지도록 설계하였기 떄문에 위와 같이 구현한 점도 있었습니다! ㅎㅎ

2024-05-21 07:13 UTC, pjm2571 commented on be/issue-tracker/src/main/java/team08/issuetracker/milestone/service/MilestoneService.java
> +    private static final String CLOSE_STATE_QUERY = "closed";
다음 번 PR 때, 망고가 구현하신 LABEL과 통합하여 개선해보도록 하겠습니다!

2024-05-22 09:45 UTC, merged