[Team04] Week3 PR
codesquad-members-2024/issue-tracker pull request #70
Opened 2024-05-24 07:47 UTC by SDL923

## 구현 내용

- Milestone의 CRUD 기능 구현
- Issue의 CRUD 기능 구현

## 질문 사항

- 기능 구현을 마치고 merge까지 끝냈는데, 해당 기능에 대해 다시 수정 사항이 생기면 브랜치명을 어떤식으로 하는게 좋을지 궁금합니다!
- 연관가 설정되어 있지만, 해당 값이 비어있을 때, null로 둬도 괜찮을까요?
    
    예를 들어, Issue와 Milestone은 1:1 관계인데, 처음 Issue를 생성할 때는 Milestone을 지정하지 않아도 돼서, milestoneId 값이 비어있는데, 이 때 보통 null로 그냥 두는지 아니면 다른 클래스로 감싸서(?) 별도로 비어있는 상태를 표시해줘야 하는지 궁금합니다!
    
- `IssueNotFoundException`과 같이 Custom Exception 클래스를 구현한 상태입니다. 이를 Service 단에서 적용하려는데, 다음과 같이 내장메서드로 구현해 놓고 사용하는 것이 자연스러운 건지 궁금합니다!
    
    ```java
    private Issue getIssueById(Long issueId) {
        return issueRepository.findById(issueId).orElseThrow(() -> new IssueNotFoundException("존재하지 않는 이슈입니다."));
    }
    ```
    
- 보통 요청 메서드 `Put`을 처리할 때, 로직 완료 후, 응답 Body에 update가 완료된 객체를 담는지, 아니면 변경된 내용만을 담는지 궁금합니다! 아니면 Body에 아무 것도 담지 않고 204 Nocontent를 응답 코드로 보내는게 맞을까요?

## 적용 예정 사항

- Test 코드 작성 예정

2024-05-25 04:30 UTC, tmdgusya requested changes
> 기능 구현을 마치고 merge까지 끝냈는데, 해당 기능에 대해 다시 수정 사항이 생기면 브랜치명을 어떤식으로 하는게 좋을지 궁금합니다!

그건 다음 리뷰에 그냥 합쳐서 올려주셔도 좋을거 같아요.

> 연관가 설정되어 있지만, 해당 값이 비어있을 때, null로 둬도 괜찮을까요? 예를 들어, Issue와 Milestone은 1:1 관계인데, 처음 Issue를 생성할 때는 Milestone을 지정하지 않아도 돼서, milestoneId 값이 비어있는데, 이 때 보통 null로 그냥 두는지 아니면 다른 클래스로 감싸서(?) 별도로 비어있는 상태를 표시해줘야 하는지 궁금합니다!

아니요. 비어져 있고 나중에 채워진다면 Null 로 두어도 좋아요~!

> IssueNotFoundException과 같이 Custom Exception 클래스를 구현한 상태입니다. 이를 Service 단에서 적용하려는데, 다음과 같이 내장메서드로 구현해 놓고 사용하는 것이 자연스러운 건지 궁금합니다!

보통 에러 핸들링을 위해 보여주신 코드처럼 Custom Error 를 많이 만들어서 쓰기는 합니다. Java 에 원래 탑재되어 있는 IllegalArgumentException 같은 것들을 많이 써보셔도 좋긴해요.

> 보통 요청 메서드 Put을 처리할 때, 로직 완료 후, 응답 Body에 update가 완료된 객체를 담는지, 아니면 변경된 내용만을 담는지 궁금합니다! 아니면 Body에 아무 것도 담지 않고 204 Nocontent를 응답 코드로 보내는게 맞을까요?

항상 정답은 없고 클라이언트(현재는 프론트엔드)에 요청에 따라 제공해주시면 될듯합니다.

----
오늘 리뷰에서 보기에 경계와 변화에 관한 부분들을 살짝 공부해보시면 좋을거 같아요. 아래 글을 읽어보면서 따라해보셔도 좋고, 같이 다른분들과 이야기 해보시면서 경계가 왜 필요하고, 캡슐화를 왜 해야하는가? 에 관한 이야기를 많이 해보시면 좋을거 같아요.

- https://martinfowler.com/eaaDev/uiArchs.html#ModelViewController

2024-05-25 04:30 UTC, tmdgusya commented on back/src/main/java/codesquad/issuetracker/config/LoginInterceptor.java
> +        if (session == null || session.getAttribute("LOGIN USER") == null) {
코드를 개발하다보면 매직넘버 이슈가 있을 수 있어서 상수는 항상 const 멤버 변수로 빼서 사용하시는걸 추천드립니다

- https://velog.io/@hwisaac/%EB%A7%A4%EC%A7%81%EB%84%98%EB%B2%84

2024-05-25 04:30 UTC, tmdgusya commented on back/src/main/java/codesquad/issuetracker/comment/CommentController.java
> +                .created(location)
👍

2024-05-25 04:30 UTC, tmdgusya commented on back/src/main/java/codesquad/issuetracker/issue/Issue.java
> +    }
이렇게 메소드 만들고 외부와 통신하는것 좋습니다👍

2024-05-25 04:30 UTC, tmdgusya commented on back/src/main/java/codesquad/issuetracker/issue/Issue.java
> +        boolean checkAssignee = assigneeIds == null || assigneeIds.stream().anyMatch(issueUserLoginIds::contains);
`checkAssignee` 라는 뜻과 `checkFilter` 라는 네이밍은 이름만 봤을때는 조금 어떤 역할을 하는지 추론하기 힘든점도 있는거 같아요. 코드로 보았을때 4부분으로 나뉘는거 같은데요. 함수가 하나의 역할을 하도록 각각 **4개의 함수로 분리**하고, 네이밍도 조금 수정 부탁드립니다. (아래 내용은 예시이므로 굳이 함수명을 따라하실 필요는 없어요.)

```
private boolean filterByAssingneeIds(List<String> assigneeIds) {
        Set<String> issueUserLoginIds = issueAssignees.stream().map(IssueAssignee::getUserLoginId).collect(Collectors.toSet());
        return assigneeIds == null || assigneeIds.stream().anyMatch(issueUserLoginIds::contains);
}

public boolean checkFilter(List<String> assigneeIds, List<Long> labelIds, Long milestoneId, String writer) {
  return filterByAssingneeIds(assigneeIds) && filterByLabelIds ...
}
```

2024-05-25 04:30 UTC, tmdgusya commented on back/src/main/java/codesquad/issuetracker/issue/IssueService.java
> +                .peek(Issue::open)
음 method 를 사용하실때 `peek` 이라는 의미를 한번 생각해보시면 좋은데요. peek 은 어원 자체도 "빨리 엿보듯이 보는 느낌이 있습니다". 아마 의도 자체가 Issue.open 을 받은 id 들의 Issue 대해 모두 Open  메소드를 실행해주는 것처럼 보이는데요.

사실 peek 자체는 엿보고 빼는 것인데, 그걸 이용해서 메소드를 실행시킨다면 조금 의미론적으로 이상하게 느껴지는 부분이 있습니다. 차라리 forEach 같은 메소드를 사용하셔서 각 엘리멘트에 대해 이걸 실행시킨다. 라는 느낌을 주시는걸 추천드려요.

2024-05-25 04:30 UTC, tmdgusya commented on back/src/main/java/codesquad/issuetracker/issue/IssueService.java
>          return (List<User>) userRepository.findAllById(assigneeNames);
요거 어디서는 List Type 이고 어디서는 Collection 타입으로 사용해서 메소드 마다 (List<XXType>) xxxx  처럼 형 변환하고 있어서 한쪽으로 통일 부탁드립니다.

2024-05-25 04:30 UTC, tmdgusya commented on back/src/main/java/codesquad/issuetracker/login/LoginController.java
> +    private final int SESSION_EXPIRATION_TIME = 60 * 60;
👍 상수사용 너무 좋습니다

2024-05-25 04:30 UTC, tmdgusya commented on back/src/test/java/codesquad/loginTest/LoginControllerTest.java
> +    public void testLoginFailure() {
테스트 좋습니다. 하나하나씩 더 많이 채워가시길 바래요👍

2024-05-25 04:30 UTC, merged

2024-05-27 11:58 UTC, yonghyeonpark commented on back/src/main/java/codesquad/issuetracker/comment/CommentController.java
> +            @RequestBody Comment comment,
글 잘 읽어보았습니다! 해당 내용 정리해서 익히고 코드에 반영해보겠습니다. 좋은 조언 감사드립니다!

2024-05-27 12:01 UTC, yonghyeonpark commented on back/src/main/java/codesquad/issuetracker/issue/IssueService.java
> +                .peek(Issue::open)
스트림에서 peek을 처음 써보는데, 메서드가 갖는 의미까지는 생각 못 해본 거 같습니다. `forEach`를 사용해서 수정해보겠습니다!

2024-05-29 02:08 UTC, SDL923 commented on back/src/main/java/codesquad/issuetracker/issue/IssueService.java
>          return (List<User>) userRepository.findAllById(assigneeNames);
넵! Repository에서 형변환 하는 방식으로 통일하겠습니다!