[TEAM08] BE - 자동 배포 기능, 이슈 기능, 필터 기능 구현
codesquad-members-2024/issue-tracker pull request #85
Opened 2024-05-29 06:04 UTC by pjm2571

# 구현한 기능

## 1) 자동 배포 기능 [ 준마이 ]
- `branch`에 배포 시, `github actions` 와 `docker` 를 이용해서 자동배포가 되도록 구현
- 도메인에 fe end-point를 연결하고, sub-domain을 생성하여 ec2 서버 인스턴스와 연결 구현

## 2) 이슈 기능 구현 [ 심바 ]
- 이슈 상세보기 기능 구현
- 이슈 목록 보기 기능 구현

## 3) 이슈 필터 기능 구현 [ 준마이 ] 
- table 조인을 사용하여 issue filter 기능 구현

## 4) 댓글 기능 구현 [ 망고 ]
- 댓글 기능 구현

## 5) S3 Upload 기능 구현 [ 준마이 ]
- s3에 이미지 첨부하는 기능 구현

---

# 추가 보완해야 할 사항

## 배포를 하면서 생긴 문제점
- 현재 `Issue` 를 삭제할 때, ddl에 cascade 옵션이 없기 때문에 삭제가 되지 않는 문제 발생!
- 현재 ddl 보완 중!

---

2024-05-29 13:27 UTC, moto6 requested changes
keystore.p12 < 요 파일이 올라왔었네요! 요건 제가 놓쳤군요! 혹시라도 유츌되었을지 모르니 기존 키파일을 제거하고 ! 꼭 새로 발급받으셔서 사용하시기 바라겠습니다!

2024-05-29 14:05 UTC, pjm2571 commented
> keystore.p12 < 요 파일이 올라왔었네요! 요건 제가 놓쳤군요! 혹시라도 유츌되었을지 모르니 기존 키파일을 제거하고 ! 꼭 새로 발급받으셔서 사용하시기 바라겠습니다!

헉!! gitignore 설정한다는 걸 깜빡했네요ㅠㅠ 
삭제 후, 재발급 받아서 actions-secret에 등록하여 새로 만들도록 수정하였습니다!!

2024-05-29 14:08 UTC, pjm2571 commented on be/issue-tracker/Dockerfile
> +ENTRYPOINT ["java", "-jar", "app.jar", "--spring.profiles.active=prod"]
좋습니다! 개선할 수 있도록 꼭 메모해놓아야겠어요!

안그래도 `페이즈마다 별도의 도커 컨테이너가 돌아가도록 구성하는 게 좋은 것인가?` 에 대해서 고민했었는데, 넘 좋네요!

2024-05-29 14:20 UTC, pjm2571 commented on be/issue-tracker/src/main/java/team08/issuetracker/comment/controller/CommentController.java
> +     * */
사실 오늘 함께 구현을 한 부분인데, 주석 제거를 미쳐 하지 못한 것 같습니다 ㅎㅎ

조금 소통에 신경쓰도록 하겠습니다!! :)

2024-05-29 14:22 UTC, pjm2571 commented on be/issue-tracker/src/main/java/team08/issuetracker/comment/service/CommentService.java
> +    @Transactional
헐.. 진짜 대박 정보입니다.. ... . . . ..

2024-05-29 14:27 UTC, pjm2571 commented on be/issue-tracker/src/main/java/team08/issuetracker/config/S3Config.java
> +}
ㅠㅠㅠ 저 진짜 intellij에 관련 설정도 해놓고 끝에 개행도 확인했는데 왜자꾸 그런걸까요...?

이렇게 되어있으면 안되는걸까요....?? 파일 끝 개행이라는 게, 33 번 라인 뒤에 엔터를 쳐서 개행을 하는 것일까요??

<img width="746" alt="image" src="https://github.com/codesquad-members-2024/issue-tracker/assets/97939207/bd6da94e-2100-4b61-9f10-3b1233904a01">

<img width="346" alt="image" src="https://github.com/codesquad-members-2024/issue-tracker/assets/97939207/eafde221-bb28-4151-b04c-2da1f80d45c3">

2024-05-29 14:28 UTC, pjm2571 commented on be/issue-tracker/src/main/java/team08/issuetracker/config/WebConfig.java
> +                        "http://192.168.1.34:3000")             // 개발용 Domain 주소
네! 좋습니다! 현재는 FE 분이 코쿼에서 작업하실때도 있고, 집 or 카페에서 작업하실때도 있어서 따로 추가하는 것으로 구현하였는데 

배포할 때는 상수로 관리해보도록 하겠습니다! ㅎㅎ

2024-05-29 14:35 UTC, pjm2571 commented on be/issue-tracker/src/main/java/team08/issuetracker/detail/dto/IssueDetailDto.java
> +    private final MilestoneSummaryDto milestone;
이슈에 대한 상세 페이지를 불러올 때, 저희가 생각했을때는 
1) 가져올 정보들이 많다
2) 하나의 api에 해당 정보를 모두 가져다 주면 프론트에서 처리하기 편할 것이다
라고 생각하여 `issue/{issueId}` 에 많이 집중되어있게 된 것 같습니다.

상세 페이지에서 다양한 기능들은 각각의 api를 통해 통신하지만, 세부 정보만 위와 같이 집중되어 있게 만들었습니다.

저는 그렇게 생각했는데, 내일 Mango와 Shimbaa에게도 한 번 여쭤보고 싶네요 ㅎㅎㅎ

---

Zoonmy Question) `issue/{issueId}` 하나의 api를 통해 `댓글`, `담당자`, `라벨`, ... 등과 같은 정보들을 한꺼번에 주는 것은 좋지 않은 구조일까요? 그렇다면, 상세 페이지를 가져올 때, `댓글 api 호출`, `담당자 api 호출`, `라벨 api 호출` ... 이렇게 많은 api를 호출하는 것이 더 좋은것일까요? 저는, api 요청이 많이 가는 것이 결국에는 서버 측 리소스 부담으로 이어질 것 같다? 생각했는데.. 생각해보기만 하고, 구현에 급급하다보니 성능 테스트를 해보지 못한 점이 아쉬움으로 많이 남았습니다 ㅠㅠ

2024-05-29 14:35 UTC, pjm2571 commented on be/issue-tracker/src/main/java/team08/issuetracker/detail/service/DetailService.java
> +}
이것들이 위의 리뷰를 남겨주신... 초거대 detail dto의 결과물로.... ㅋㅋㅋㅋㅋ

2024-05-29 14:36 UTC, pjm2571 commented on be/issue-tracker/src/main/java/team08/issuetracker/exception/ErrorResponse.java
> +    public ErrorResponse(Exception e) {
넵 반영하겠습니다!

2024-05-29 14:45 UTC, pjm2571 commented on be/issue-tracker/src/main/java/team08/issuetracker/filter/controller/FilterController.java
> +            @RequestParam(required = false) Long milestone_id
오호 이 부분을 구현하면서 고민이 많았습니다!

## 문제점
- `BE` : 자바에서는 카멜 케이스로 해야한다!
- `FE` : url에 쿼리 스트링으로 들어갈 값인데, snakeCase로 받고싶다!

## 해결
### 현재 해결법
- 단순히 매개 변수 인자를 `snake Case`로 하면 문제 해결(?) 이 될 것 이라 생각
  - 하지만 결국에, 어떤 controller에서는 camelCase를, 어떤 controller에서는 snakeCase를 쓰면서 코드 컨벤션이 깨지게 되고 혼란이 가중될 수 있다!
### 생각해낸 해결법
 `Jackson` 사용
- JSON 필드 네이밍 전략을 변경하여 snake_case 형식을 지원하도록 Jackson ObjectMapper를 구성
```
spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
```
- request dto 수정
```
@JsonProperty("label_id")
private Long labelId;
@JsonProperty("milestone_id")
private Long milestoneId;
```
- controller 수정
```
...
@RequestParam(name = "label_id", required = false) Long labelId,
@RequestParam(name = "milestone_id", required = false) Long milestoneId
...

인데 내일 한 번 팀원들과 상의해서 개선해보겠습니다~~ 👍

2024-05-29 14:46 UTC, pjm2571 commented on be/issue-tracker/src/main/java/team08/issuetracker/filter/controller/FilterController.java
> +            @RequestParam(required = false) Long milestone_id
이 부분도 같이 개선해보겠습니다!

2024-05-29 14:47 UTC, pjm2571 commented on be/issue-tracker/src/main/java/team08/issuetracker/filter/service/FilterService.java
> +        return openedCount;
넵!!! count를 구하는 메서드, detailIssue 작업 메서드로 분리하여 개선해보도록 하겠습니다 !

2024-05-29 14:48 UTC, pjm2571 commented on be/issue-tracker/src/main/java/team08/issuetracker/filter/service/FilterService.java
> +public class FilterService {
아하! 사실 `Controller` - `Service` - `Repository` 에 너무 어울리지 않는다고 생각해서... `@Service`라는 어노테이션을 사용하는 것이 맞는가에 대해 고민을 많이 했었는데, `@Component`라는 어노테이션이 있었군요..! _저의 스프링 지식 무지함을 느꼈습니다..._

이것또한 개선해보겠습니다!!!!

2024-05-29 14:49 UTC, pjm2571 commented on be/issue-tracker/src/main/java/team08/issuetracker/filter/service/FilterService.java
> +    }
네 Opitona.ofNullable이라는 메소드를 심바가 말씀해주셨는데, 적용해본다는 것이 그냥 넘어갔네요! 리팩토링 해보겠습니다~

2024-05-29 14:51 UTC, pjm2571 commented on be/issue-tracker/build.gradle
> +    implementation 'com.mysql:mysql-connector-j:8.3.0' // mysql 의존성 추가
아 그리고, `spring-profile` 기능은 어떨 때, 쓰면 좋을까???

에 대해서도 궁금해졌습니다. 혹시 실무에서도 많이 쓰는 기능일까요?!

2024-05-31 00:28 UTC, moto6 commented on be/issue-tracker/Dockerfile
> +ENTRYPOINT ["java", "-jar", "app.jar", "--spring.profiles.active=prod"]
넵 좋습니다! 지금은 어떻게 하느냐면 도커파일에 환경변수를 지정하지 않고 실행시키는 시점에 환경변수로 넘겨주고 있는데요 
(리눅스 쉘 스크립트 기준)
```sh
export SPRING_PROFILES_ACTIVE=dev
```
요렇게 환경변수를 전달해주고 있어요! 다른 좋은 방법이 많겠지만 상황과 환경에 따라 적절한 방법이 다르니  결국 중요한 메시지는 "도커파일 99% 같고 환경변수 하나만 다른걸 굳이 여러버전으로 가지고 있을 필요는 없을까?" 하는 의문점을 가져주시는것만으로도 지금은 아주 좋은 성장과정이라고 생각합니다!

2024-05-31 00:41 UTC, moto6 commented on be/issue-tracker/build.gradle
> +    implementation 'com.mysql:mysql-connector-j:8.3.0' // mysql 의존성 추가
@pjm2571  아하 요부분 제 의견 공유드려보면요! 

## 1) 디비선택 : h2 vs mysql 
- 이게 h2 가 간편하게 쓰기는 좋은데 데이터 저장해놓기가 애매한 부분이 있고 인덱스 등.. h2 에는 미구현된 기능도 몇가지가 있어서 로컬에서도 docker 같은걸로 mysql 띄워놓고 구동하는 방법을 쓰고 있어요 
- 인프라세팅에 따라 다르긴 하는데, 로컬개발환경도 dev DB 를 바라보게 해서 로컬,dev 가 DB 를 공유하게 하면  특정 데이터로 인해 생기는 문제를 공유하고 빠르게 해결하는데 도움이 되기도 하는데요, 요러면 단점이 dev DB 가 URL 로 인터넷 노출되어야만 하는 부분이 있어서 인프라적인 작업이 필요하고(인프라작업 = 3306 포트 말고 다른 포트번호로 쓴다던지, mysql 루트계정관리 등..) 그런데 아무리 dev DB 라도 외부에 접근포인트가 노출되는거는 위험한 느낌은 있는거같습니다..!

## 2) spring-profile 기능 사용
- 네 이게 없으면 아마 아주 곤란할꺼같아요 ! 꼭 필요하고 실무에서 많이 쓰는걸 넘어서 무조건 쓴다! 요렇게 말씀드리고 싶은데요, 지금은 dev 서버에다가만 배포해두고 데모하는 방식인데요
- 샘플을 보여드리면 더 좋을꺼같은데요 https://issues.apache.org/jira/projects/ZEPPELIN << 아파치 제플린이라는 오픈소스 프로젝트의 이슈 트레커인데요, 요 이슈트레커를 "실제로 사용하는 사용자 = 아파치 제플린 개발자" 들이랑 "이슈트래커 시스템 개발자" 랑은 다른계층이고 (아마 회사도 조직도 다르겠죠?) 관심사도 다르고 테스트용 데이터가 운영환경에 섞여들어가면 안되고 반대도 마찬가지이고 dev 에서는 안정적이지 않은걸 올리고 테스트하면서 이슈를 해결해가는 과정이 필요하기 때문에 그렇습니다!

2024-05-31 00:43 UTC, moto6 commented on be/issue-tracker/src/main/java/team08/issuetracker/filter/service/FilterService.java
> +    }
아주좋습니다 ! 

https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/util/Optional.html

제가 예전에 답변하지 못했던 면접질문 하나 뽀나스로 공유드리면 
```
API Note:
Optional is primarily intended for use as a method return type where there is a clear need to represent "no result," and where using null is likely to cause errors. A variable whose type is Optional should never itself be null; it should always point to an Optional instance.
```

요 포인트도 기억해주시면 아주 좋을꺼같아요!

2024-06-03 01:13 UTC, merged